// Generated by CoffeeScript 1.3.3
var Browl;

Browl = (function() {
  var defaults, notifications;

  function Browl() {}

  notifications = {};

  defaults = {
    container: {
      "class": ".browl-container",
      position: "top-right"
    },
    notification: {
      "class": ".browl-notification",
      template: function(icon, title, message) {
        if (icon == null) {
          icon = "";
        }
        if (title == null) {
          title = "";
        }
        if (message == null) {
          message = "";
        }
        return $("<li class='browl-notification out'><div class='icon'>" + icon + "</div><div class='content'><div class='title'>" + title + "</div><div class='message'>" + message + "</div></div></li>");
      }
    }
  };

  Browl.notify = function() {
    var $container, $notification, $template;
    $container = $(defaults.container["class"]);
    $template = defaults.notification.template.apply(this, arguments);
    $notification = $template.appendTo($container);
    $container.width($container.width());
    $notification.removeClass("out");
    return setTimeout(function() {
      $notification.on("webkitTransitionEnd transitionend", function() {
        return $notification.remove();
      });
      return $notification.css({
        opacity: 0,
        marginTop: -$notification.outerHeight() + 1
      });
    }, 5000);
  };

  return Browl;

})();
